# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crimeAnalysis.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='crimeAnalysis.proto',
  package='CirmeAnalysis',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13\x63rimeAnalysis.proto\x12\rCirmeAnalysis\"\x89\x04\n\tCrimeData\x12\x10\n\x08Metadata\x18\x01 \x01(\t\x12.\n\x07\x61llData\x18\x02 \x03(\x0b\x32\x1d.CirmeAnalysis.CrimeData.Data\x1a\x44\n\x0btime_extend\x12\x11\n\tstartTime\x18\x01 \x01(\t\x12\x10\n\x08stopTime\x18\x02 \x01(\t\x12\x10\n\x08timeStep\x18\x03 \x01(\x01\x1aL\n\x06\x45xtend\x12\x0f\n\x07spaceX1\x18\x01 \x01(\x01\x12\x0f\n\x07spaceX2\x18\x02 \x01(\x01\x12\x0f\n\x07spaceY1\x18\x03 \x01(\x01\x12\x0f\n\x07spaceY2\x18\x04 \x01(\x01\x1a\xfc\x01\n\x04\x44\x61ta\x12\x0f\n\x07gridRow\x18\x01 \x01(\x05\x12\x12\n\ngridColumn\x18\x02 \x01(\x05\x12\x0c\n\x04time\x18\x03 \x01(\t\x12\x10\n\x08\x63rimeNum\x18\x04 \x01(\x05\x12\r\n\x05gridX\x18\x05 \x01(\x01\x12\r\n\x05gridY\x18\x06 \x01(\x01\x12\x13\n\x0b\x64istancePol\x18\x07 \x01(\x01\x12\x13\n\x0b\x64istanceBus\x18\x08 \x01(\x01\x12\x0f\n\x07weather\x18\t \x01(\x05\x12\x13\n\x0blanduseTown\x18\n \x01(\x01\x12\x16\n\x0elanduseVillage\x18\x0b \x01(\x01\x12\x13\n\x0blanduseCons\x18\x0c \x01(\x01\x12\x14\n\x0clanduseOther\x18\r \x01(\x01\x1a\'\n\x04Grid\x12\x10\n\x08gridSize\x18\x01 \x01(\x01\x12\r\n\x05layer\x18\x02 \x01(\x05\x62\x06proto3')
)




_CRIMEDATA_TIME_EXTEND = _descriptor.Descriptor(
  name='time_extend',
  full_name='CirmeAnalysis.CrimeData.time_extend',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='startTime', full_name='CirmeAnalysis.CrimeData.time_extend.startTime', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stopTime', full_name='CirmeAnalysis.CrimeData.time_extend.stopTime', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeStep', full_name='CirmeAnalysis.CrimeData.time_extend.timeStep', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=186,
)

_CRIMEDATA_EXTEND = _descriptor.Descriptor(
  name='Extend',
  full_name='CirmeAnalysis.CrimeData.Extend',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='spaceX1', full_name='CirmeAnalysis.CrimeData.Extend.spaceX1', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='spaceX2', full_name='CirmeAnalysis.CrimeData.Extend.spaceX2', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='spaceY1', full_name='CirmeAnalysis.CrimeData.Extend.spaceY1', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='spaceY2', full_name='CirmeAnalysis.CrimeData.Extend.spaceY2', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=264,
)

_CRIMEDATA_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='CirmeAnalysis.CrimeData.Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gridRow', full_name='CirmeAnalysis.CrimeData.Data.gridRow', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gridColumn', full_name='CirmeAnalysis.CrimeData.Data.gridColumn', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='CirmeAnalysis.CrimeData.Data.time', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='crimeNum', full_name='CirmeAnalysis.CrimeData.Data.crimeNum', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gridX', full_name='CirmeAnalysis.CrimeData.Data.gridX', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gridY', full_name='CirmeAnalysis.CrimeData.Data.gridY', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='distancePol', full_name='CirmeAnalysis.CrimeData.Data.distancePol', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='distanceBus', full_name='CirmeAnalysis.CrimeData.Data.distanceBus', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weather', full_name='CirmeAnalysis.CrimeData.Data.weather', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='landuseTown', full_name='CirmeAnalysis.CrimeData.Data.landuseTown', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='landuseVillage', full_name='CirmeAnalysis.CrimeData.Data.landuseVillage', index=10,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='landuseCons', full_name='CirmeAnalysis.CrimeData.Data.landuseCons', index=11,
      number=12, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='landuseOther', full_name='CirmeAnalysis.CrimeData.Data.landuseOther', index=12,
      number=13, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=267,
  serialized_end=519,
)

_CRIMEDATA_GRID = _descriptor.Descriptor(
  name='Grid',
  full_name='CirmeAnalysis.CrimeData.Grid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gridSize', full_name='CirmeAnalysis.CrimeData.Grid.gridSize', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='layer', full_name='CirmeAnalysis.CrimeData.Grid.layer', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=521,
  serialized_end=560,
)

_CRIMEDATA = _descriptor.Descriptor(
  name='CrimeData',
  full_name='CirmeAnalysis.CrimeData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Metadata', full_name='CirmeAnalysis.CrimeData.Metadata', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='allData', full_name='CirmeAnalysis.CrimeData.allData', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CRIMEDATA_TIME_EXTEND, _CRIMEDATA_EXTEND, _CRIMEDATA_DATA, _CRIMEDATA_GRID, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=560,
)

_CRIMEDATA_TIME_EXTEND.containing_type = _CRIMEDATA
_CRIMEDATA_EXTEND.containing_type = _CRIMEDATA
_CRIMEDATA_DATA.containing_type = _CRIMEDATA
_CRIMEDATA_GRID.containing_type = _CRIMEDATA
_CRIMEDATA.fields_by_name['allData'].message_type = _CRIMEDATA_DATA
DESCRIPTOR.message_types_by_name['CrimeData'] = _CRIMEDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CrimeData = _reflection.GeneratedProtocolMessageType('CrimeData', (_message.Message,), dict(

  time_extend = _reflection.GeneratedProtocolMessageType('time_extend', (_message.Message,), dict(
    DESCRIPTOR = _CRIMEDATA_TIME_EXTEND,
    __module__ = 'crimeAnalysis_pb2'
    # @@protoc_insertion_point(class_scope:CirmeAnalysis.CrimeData.time_extend)
    ))
  ,

  Extend = _reflection.GeneratedProtocolMessageType('Extend', (_message.Message,), dict(
    DESCRIPTOR = _CRIMEDATA_EXTEND,
    __module__ = 'crimeAnalysis_pb2'
    # @@protoc_insertion_point(class_scope:CirmeAnalysis.CrimeData.Extend)
    ))
  ,

  Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), dict(
    DESCRIPTOR = _CRIMEDATA_DATA,
    __module__ = 'crimeAnalysis_pb2'
    # @@protoc_insertion_point(class_scope:CirmeAnalysis.CrimeData.Data)
    ))
  ,

  Grid = _reflection.GeneratedProtocolMessageType('Grid', (_message.Message,), dict(
    DESCRIPTOR = _CRIMEDATA_GRID,
    __module__ = 'crimeAnalysis_pb2'
    # @@protoc_insertion_point(class_scope:CirmeAnalysis.CrimeData.Grid)
    ))
  ,
  DESCRIPTOR = _CRIMEDATA,
  __module__ = 'crimeAnalysis_pb2'
  # @@protoc_insertion_point(class_scope:CirmeAnalysis.CrimeData)
  ))
_sym_db.RegisterMessage(CrimeData)
_sym_db.RegisterMessage(CrimeData.time_extend)
_sym_db.RegisterMessage(CrimeData.Extend)
_sym_db.RegisterMessage(CrimeData.Data)
_sym_db.RegisterMessage(CrimeData.Grid)


# @@protoc_insertion_point(module_scope)
